version: "3.7"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  oauth-proxy:
    build:
      context: ./oauthkeeper
    command:
      - --config
      - /config.yaml
      - serve
    networks:
      - frontend
    ports:
      - "4455"
      - "4456"

  nginx-proxy:
    build:
      context: ./proxy
    ports:
      - "8081:8081"
    depends_on:
      - kratos
      - frontend
    networks:
      - frontend

  kratos:
    build:
      context: .
    depends_on:
      - database
    networks:
      - frontend
      - backend
    ports:
      - "4434"
      - "4433"

  backend:
    image: node:14
    volumes:
      - ./backend:/app
    working_dir: /app
    entrypoint:
      - node
      - app
    ports:
      - "3355"
    networks:
      - frontend
      - backend

  frontend:
    image: node:14
    volumes:
      - ./frontend/test:/app
    working_dir: /app
    entrypoint:
      - npm
      - run
      - serve
    networks:
      - frontend
    ports:
      - "8080"

#  kratos-selfservice-ui-node:
#    image: oryd/kratos-selfservice-ui-node:v0.8.2-alpha.1
#    ports:
#      - "4466:4455"
#    links:
#      - "kratos"
#    environment:
#      - PORT=4455
#      - SECURITY_MODE=
#      - KRATOS_PUBLIC_URL=http://kratos:4433/
#      - KRATOS_BROWSER_URL=http://ui.my-app.com:4000/.ory/
#    networks:
#      - backend
#    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - backend

  database:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - backend

#  db-admin:
#    image: dpage/pgadmin4:6.2
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "8080:80"
#    networks:
#      - backend
